version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
    day: sunday
  labels:
  - github-actions
  - dependencies
- package-ecosystem: gomod
  directory: /
  schedule:
    interval: weekly
    day: sunday
  labels:
  - gomod
  - dependencies
  groups:
    all:
      patterns:
      - '*'
