// -*- Mode: Go; indent-tabs-mode: t -*-
//
// Copyright (C) 2022 Intel Corporation
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by gen_commands.py DO NOT EDIT.

package event

type CreatePullPointSubscriptionFunction struct{}

func (_ *CreatePullPointSubscriptionFunction) Request() any {
	return &CreatePullPointSubscription{}
}
func (_ *CreatePullPointSubscriptionFunction) Response() any {
	return &CreatePullPointSubscriptionResponse{}
}

type GetEventPropertiesFunction struct{}

func (_ *GetEventPropertiesFunction) Request() any {
	return &GetEventProperties{}
}
func (_ *GetEventPropertiesFunction) Response() any {
	return &GetEventPropertiesResponse{}
}

type GetServiceCapabilitiesFunction struct{}

func (_ *GetServiceCapabilitiesFunction) Request() any {
	return &GetServiceCapabilities{}
}
func (_ *GetServiceCapabilitiesFunction) Response() any {
	return &GetServiceCapabilitiesResponse{}
}

type PullMessagesFunction struct{}

func (_ *PullMessagesFunction) Request() any {
	return &PullMessages{}
}
func (_ *PullMessagesFunction) Response() any {
	return &PullMessagesResponse{}
}

type RenewFunction struct{}

func (_ *RenewFunction) Request() any {
	return &Renew{}
}
func (_ *RenewFunction) Response() any {
	return &RenewResponse{}
}

type SeekFunction struct{}

func (_ *SeekFunction) Request() any {
	return &Seek{}
}
func (_ *SeekFunction) Response() any {
	return &SeekResponse{}
}

type SetSynchronizationPointFunction struct{}

func (_ *SetSynchronizationPointFunction) Request() any {
	return &SetSynchronizationPoint{}
}
func (_ *SetSynchronizationPointFunction) Response() any {
	return &SetSynchronizationPointResponse{}
}

type SubscribeFunction struct{}

func (_ *SubscribeFunction) Request() any {
	return &Subscribe{}
}
func (_ *SubscribeFunction) Response() any {
	return &SubscribeResponse{}
}

type SubscriptionReferenceFunction struct{}

func (_ *SubscriptionReferenceFunction) Request() any {
	return &SubscriptionReference{}
}
func (_ *SubscriptionReferenceFunction) Response() any {
	return &SubscriptionReferenceResponse{}
}

type UnsubscribeFunction struct{}

func (_ *UnsubscribeFunction) Request() any {
	return &Unsubscribe{}
}
func (_ *UnsubscribeFunction) Response() any {
	return &UnsubscribeResponse{}
}
