// -*- Mode: Go; indent-tabs-mode: t -*-
//
// Copyright (C) 2022 Intel Corporation
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by gen_commands.py DO NOT EDIT.

package imaging

type GetCurrentPresetFunction struct{}

func (_ *GetCurrentPresetFunction) Request() any {
	return &GetCurrentPreset{}
}
func (_ *GetCurrentPresetFunction) Response() any {
	return &GetCurrentPresetResponse{}
}

type GetImagingSettingsFunction struct{}

func (_ *GetImagingSettingsFunction) Request() any {
	return &GetImagingSettings{}
}
func (_ *GetImagingSettingsFunction) Response() any {
	return &GetImagingSettingsResponse{}
}

type GetMoveOptionsFunction struct{}

func (_ *GetMoveOptionsFunction) Request() any {
	return &GetMoveOptions{}
}
func (_ *GetMoveOptionsFunction) Response() any {
	return &GetMoveOptionsResponse{}
}

type GetOptionsFunction struct{}

func (_ *GetOptionsFunction) Request() any {
	return &GetOptions{}
}
func (_ *GetOptionsFunction) Response() any {
	return &GetOptionsResponse{}
}

type GetPresetsFunction struct{}

func (_ *GetPresetsFunction) Request() any {
	return &GetPresets{}
}
func (_ *GetPresetsFunction) Response() any {
	return &GetPresetsResponse{}
}

type GetServiceCapabilitiesFunction struct{}

func (_ *GetServiceCapabilitiesFunction) Request() any {
	return &GetServiceCapabilities{}
}
func (_ *GetServiceCapabilitiesFunction) Response() any {
	return &GetServiceCapabilitiesResponse{}
}

type GetStatusFunction struct{}

func (_ *GetStatusFunction) Request() any {
	return &GetStatus{}
}
func (_ *GetStatusFunction) Response() any {
	return &GetStatusResponse{}
}

type MoveFunction struct{}

func (_ *MoveFunction) Request() any {
	return &Move{}
}
func (_ *MoveFunction) Response() any {
	return &MoveResponse{}
}

type SetCurrentPresetFunction struct{}

func (_ *SetCurrentPresetFunction) Request() any {
	return &SetCurrentPreset{}
}
func (_ *SetCurrentPresetFunction) Response() any {
	return &SetCurrentPresetResponse{}
}

type SetImagingSettingsFunction struct{}

func (_ *SetImagingSettingsFunction) Request() any {
	return &SetImagingSettings{}
}
func (_ *SetImagingSettingsFunction) Response() any {
	return &SetImagingSettingsResponse{}
}

type StopFunction struct{}

func (_ *StopFunction) Request() any {
	return &Stop{}
}
func (_ *StopFunction) Response() any {
	return &StopResponse{}
}
